[package]
name = "quickstart"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
log = "0.4"
tokio = "1.36.0"
async-trait = "0.1.78"

ygw = { path = "../ygw", features = ["socketcan"]}
ygw-macros = {path = "../ygw-macros"}
